# config/initializers/rails_audit_log.rb
# Generated by `bin/rails generate rails_audit_log:initializer`
#
# All settings are optional. Remove the comments around any line you want to activate.

RailsAuditLog.configure do |config|
  # Global columns excluded from all audited models. Default: ["updated_at"]
  # config.ignored_attributes = %w[updated_at cached_at]

  # Store a full attribute snapshot alongside object_changes. Default: true
  # Disable to save storage; reify and version_at fall back to diff-only reconstruction.
  # config.store_snapshot = false

  # Capture remote_ip and user_agent into each entry's metadata column. Default: false
  # Requires including RailsAuditLog::Controller in ApplicationController.
  # config.capture_request_metadata = true

  # Customise how the actor's display name is stored at write time. Default: actor.name
  # config.whodunnit_display = ->(actor) { actor.email }

  # Global cap on entries retained per tracked record. Default: nil (no limit)
  # Per-model `audit_log version_limit: N` takes precedence.
  # config.version_limit = 100

  # Write all audit entries asynchronously via WriteAuditLogJob. Default: false
  # Per-model `audit_log async: true` also works.
  # config.async = true

  # Route AuditLogEntry to a dedicated database (Rails multi-DB). Default: nil
  # config.connects_to = { database: { writing: :audit_log, reading: :audit_log } }
end