# config/initializers/rails_audit_log_encryption.rb
# Generated by `bin/rails generate rails_audit_log:encryption`
#
# == Setup
#
# 1. Run `bin/rails db:encryption:init` to generate encryption keys and store
#    them in config/credentials.yml.enc under the :active_record_encryption key.
#
#    Rails adds entries like:
#      active_record_encryption:
#        primary_key: <generated>
#        deterministic_key: <generated>
#        key_derivation_salt: <generated>
#
# 2. Wire the keys into ActiveRecord::Encryption (already done below).
#
# 3. Enable encryption globally or per model:
#
#      # Global — every audited model encrypts by default:
#      # RailsAuditLog.encrypt = true
#
#      # Per model — opt individual models in:
#      # class Payment < ApplicationRecord
#      #   include RailsAuditLog::Auditable
#      #   audit_log encrypt: true
#      # end
#
#      # Per model — opt a model out when the global default is on:
#      # class PublicLog < ApplicationRecord
#      #   include RailsAuditLog::Auditable
#      #   audit_log encrypt: false
#      # end

Rails.application.configure do
  config.active_record.encryption.primary_key =
    Rails.application.credentials.dig(:active_record_encryption, :primary_key)
  config.active_record.encryption.deterministic_key =
    Rails.application.credentials.dig(:active_record_encryption, :deterministic_key)
  config.active_record.encryption.key_derivation_salt =
    Rails.application.credentials.dig(:active_record_encryption, :key_derivation_salt)
end